#!/bin/sh
ssh ubuntu@3.38.55.36 <<EOF
    cd ~/ovni
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install 18.18.2
    npm install
    npm install -g pm2
    pm2 install typescript
    pm2 restart ecosystem.config.js
    exit
EOF
