#!/bin/bash

# nvm 초기화
source /var/lib/jenkins/.nvm/nvm.sh

# 프로젝트 디렉토리로 이동
cd /var/lib/jenkins/workspace/Common-View

# npm 설치 및 종속성 설치
npm install

# pm2 설치
sudo npm install pm2 -g

# pm2 실행 (ecosystem.config.js 파일 필요)
pm2 start ecosystem.config.js

# 기타 작업 수행
# ...

# 스크립트 종료
exit 0